update all deps to ethers v6
tablelandnetwork/studio pull request #266
Opened 2024-05-02 23:59 UTC by joewagner

2024-05-03 01:08 UTC, joewagner commented
@dtbuchholz Aaron and I decided to remove the staging branch and start going straight to main with studio PRs.  Looks like #260 was closed when Aaron removed the staging branch, so I'm opening this PR in place of that. 
I deployed `next` versions of everything. Feel free to test out the cli and the vercel deployment of this pr.
Some stuff seems to work, and some does not.  I'll dig in more tomorrow.

2024-05-03 02:39 UTC, dtbuchholz commented
Ok gotcha, sgtm. Lmk if I need to jump back in on anything I semi-broke hah but will test those that are working out

2024-05-03 09:50 UTC, joewagner commented
Actually, I realized that I forgot to push the pre-release versions to this PR.  Hence, the vercel deployment didn't have the right deps.
I pushed those changes and everything seems to be working well.  It looks like Amoy is down now. It stopped mining blocks about 20 minutes ago so I can't test that anymore.  But I was able to create a table there with the web app and cli.

2024-05-06 16:55 UTC, joewagner commented
The is ready for a final review

2024-05-07 15:40 UTC, dtbuchholz commented on packages/chains/src/index.ts
> +      name: "OK LINK",
small impact, but we can update this to polygonscan https://github.com/tablelandnetwork/studio/pull/269

2024-05-07 15:41 UTC, dtbuchholz submitted a review, later dismissed
lgtm

2024-05-09 20:33 UTC, asutula reviewed
Few comments and questions and one little thing to change.

2024-05-09 20:33 UTC, asutula commented on packages/chains/src/index.ts
> +// Note: copied from viem@2.9.22
Just curious why we don't upgrade viem?

2024-05-09 20:33 UTC, asutula commented on packages/cli/package.json
> +    "@trpc/server": "^11.0.0-next-beta.318"
Didn't think packages should have devDependencies. Don't they go in the root package.json?

2024-05-09 20:33 UTC, asutula commented on packages/web/app/[team]/(team)/people/page.tsx
>                    membership={teamAuthorization!}
I think you can just remove the `!` and the eslint disable line.

2024-05-09 20:33 UTC, asutula commented on packages/web/package.json
> +    "@tableland/studio-validators": "^0.0.1",
Mayne it doesn't hurt to put these versions in here, but it might just be extra work. I think you can just use `""` or maybe `"*"` and it will just resolve the local monorepo packages.

2024-05-09 20:37 UTC, dtbuchholz commented on packages/chains/src/index.ts
> +// Note: copied from viem@2.9.22
no reason—i just figured i'd reduce the amount of "new" things in this PR. i _did_ just update the docs with how to do use wagmi/viem v2 [here](https://docs.tableland.xyz/playbooks/frameworks/wagmi) as well as in this nextjs template [here](https://github.com/tablelandnetwork/next-ts-tableland-template/tree/main/src), in case we want to update the studio.

2024-05-09 20:43 UTC, dtbuchholz commented on packages/cli/package.json
> +    "@trpc/server": "^11.0.0-next-beta.318"
i'm not sure exactly how lerna differs from a single package setup, so i had assumed it was just a package-level thing, but i could def be wrong. 

for context—i added this as a dev dep because it's required in tests but wasn't listed in either the package's or root's package.json file. and, i was having an issue with trpc in one of the tests, so i wanted to make sure that trpc package versions wasn't an issue.

2024-05-09 21:12 UTC, joewagner commented on packages/web/package.json
> +    "@tableland/studio-validators": "^0.0.1",
It _feels_ wrong to use "*" or "", but I probably don't fully understand the implications.  Are there docs or a blog post that explain the nuances of "*" and "" in a monorepo package that isn't published?

I pretty sure we don't want to do that for any packages that get published to npm, (i.e. only `web` can get away with using "*"), right?

2024-05-13 15:42 UTC, joewagner commented on packages/cli/package.json
> +    "@trpc/server": "^11.0.0-next-beta.318"
This should be at the root. It's not related to lerna, but npm workspaces makes all root devDeps available to tests and local dev.

2024-05-13 17:01 UTC, asutula commented on packages/web/package.json
> +    "@tableland/studio-validators": "^0.0.1",
Right, I'm just talking about the `web` package since it is never published. I need to learn more about all this. Just seemed like a way to do a little less work, but we don't need to change this now if we don't want.

2024-05-13 17:40 UTC, joewagner commented on packages/web/package.json
> +    "@tableland/studio-validators": "^0.0.1",
That sounds good to me.  I'll push this change and the one above @dtbuchholz commented on now.

2024-05-17 19:11 UTC, joewagner commented on packages/web/package.json
> +    "react-dom": "18.3.1",
pinning at these three versions and the associate type packages seems to work.  I the future let's update these carefully and in a specific update PR.

2024-05-17 19:13 UTC, joewagner commented
After fighting with quite a few different version conflict issues, I've got this rebased and back to passing CI.
@asutula @dtbuchholz give this another review when convenient.

2024-05-20 16:53 UTC, asutula requested changes

2024-05-20 16:53 UTC, asutula commented on .vscode/settings.json
Can we revert this? Seems like something that is covered in our eslint config, not sure why it should be here as well.

2024-05-20 16:53 UTC, asutula commented on packages/web/app/[team]/(team)/people/page.tsx
>                    membership={teamAuthorization!}
@joewagner can you make this change?

2024-05-20 16:53 UTC, asutula commented on packages/web/app/[team]/(team)/people/page.tsx
>                    membership={teamAuthorization!}
```suggestion
                  membership={teamAuthorization}
```

2024-05-20 19:33 UTC, dtbuchholz commented on .vscode/settings.json
In my VSCode instance, if this isn't here, then eslint complains about imports in every package/file. So I added it, and it silenced those warnings.

You don't get any eslint warnings if this isn't included? Cuz maybe there's a global setting I need to adjust.

2024-05-20 20:31 UTC, joewagner commented on .vscode/settings.json
I don't use vscode features very heavily, so I don't have a preference what we do here.

2024-05-20 21:47 UTC, dtbuchholz commented on .vscode/settings.json
whatever you guys want! for reference, if i remove it, this is how every file looks on my machine
<img width="915" alt="Screenshot 2024-05-20 at 2 46 13 PM" src="https://github.com/tablelandnetwork/studio/assets/13358940/3b06b812-eb02-4429-93f2-3bb2c9e2548c">

2024-05-20 22:23 UTC, asutula commented on .vscode/settings.json
Oh, you know, I disabled the ESLint extension in VSCode because of this error hahah! Ok cool, let's keep this and I can enable the extension again. For the record, something isn't right with our eslint monorepo setup, and it's causing these problems. Will have to solve this at some point.

2024-05-20 22:23 UTC, asutula approved these changes

2024-05-21 04:57 UTC, merged