(web) add a console component that allows running sql in the context of an env
tablelandnetwork/studio pull request #293
Opened 2024-06-28 14:31 UTC by joewagner

2024-07-02 20:21 UTC, asutula commented
Just saw this @joewagner. Sorry for the delay. Will answer your questions this afternoon asap.

2024-07-02 20:40 UTC, joewagner commented
> Just saw this @joewagner. Sorry for the delay. Will answer your questions this afternoon asap.

No worries, I think I forgot to request a review

2024-07-02 22:19 UTC, asutula requested changes
This is awesome! So cool to see and use this. Requests some changes, then we can get this merged.

2024-07-02 22:19 UTC, asutula commented on packages/web/app/[team]/[project]/_components/sidebar.tsx
> +  const isConsole = pathParts.length === 5 && pathParts.pop() === "console";
I do have a suggestion that is a bit cleaner:

You can rely on the values returned by `useParams` above to distinguish between  the `console` part of the route and any table name. If the user is visiting the `console` page, `defSlug` will be `undefined`. So this give us most of the information we need to make sure we're not viewing a table (def), but we still need to distinguish between the overview page and console page which both match the case `!!envSlug && !defSlug`. We can use the hook `useSelectedLayoutSegments` to get a nice array of url segments below the layout without needing to split the pathname string on `/` etc (as you complain about below). So the final calculation of `isConsole` would be:

```
const isConsole =
    !!envSlug && !defSlug && selectedLayoutSegments.slice(-1)[0] === "console";
```

2024-07-02 22:19 UTC, asutula commented on packages/web/app/[team]/[project]/_components/sidebar.tsx
> +  const isConsole = pathParts.length === 5 && pathParts.pop() === "console";
We should, for now at least, just go with the restricted slug approach. There is no table def named `console` yet (I checked using your console!), so we can implement that restriction with no problem currently.

![Screenshot 2024-07-02 at 4 15 32 PM](https://github.com/tablelandnetwork/studio/assets/528969/859b75b3-67e3-45d1-be45-fefcc617fad4)

2024-07-02 22:19 UTC, asutula commented on packages/web/app/[team]/[project]/_components/sidebar.tsx
> +            !defSlug && !!envSlug && !isConsole && envSlug === env?.slug
Addressed this in the comment above. Let's just not allow that table name for now. Maybe we migrate to a different url structure in the future.

2024-07-02 22:26 UTC, asutula commented on packages/web/app/[team]/[project]/_components/sidebar.tsx
>          />
This `SidebarLink` should go in the `SidebarSection` above along with the link for Overview. You can then delete this section.

2024-07-02 23:06 UTC, joewagner commented on packages/web/app/[team]/[project]/[env]/console/page.tsx
> +  }
Oh perfect!

2024-07-02 23:11 UTC, joewagner commented on packages/web/app/prism.js
Prismjs seems to be optimized to be downloaded and used in this way.  The npm package only include a few types of highlighting/formatting.  Since we want sql highlighting I had to download the specific theme and formatting.

2024-07-02 23:13 UTC, joewagner commented on packages/web/package.json
> +    "prismjs": "^1.28.0",
Good catch.  I tried to use npm and avoid including the prismjs source, but when that didn't work I forgot to remove the dep here.

2024-07-03 15:51 UTC, joewagner commented on packages/web/app/[team]/[project]/_components/sidebar.tsx
> +  const isConsole = pathParts.length === 5 && pathParts.pop() === "console";
>  We can use the hook useSelectedLayoutSegments to get a nice array of url segments below the layout without needing to split the pathname string on / etc (as you complain about below). So the final calculation of `isConsole` would be:
> 
> ```
> const isConsole =
>     !!envSlug && !defSlug && selectedLayoutSegments.slice(-1)[0] === "console";
> ```

The `useSelectedSegments` hook works well, I'll switch to that. 

> We should, for now at least, just go with the restricted slug approach. There is no table def named console yet (I checked using your console!), so we can implement that restriction with no problem currently.

I'll set it up so that "console" is a reserved word within the context of defs.  A similar problem exists if you create an environment called "settings". should I work on fixing that here, or leave it for another PR?

2024-07-03 20:03 UTC, joewagner commented
@asutula I believe I got all the change requests in here.  Have another look when you get time.

2024-07-08 16:17 UTC, asutula approved these changes

2024-07-08 16:58 UTC, merged